---
- name: Pull Docker Image of Calculator and Scan with Trivy
  hosts: all

  tasks:
    - name: Start Minikube
      shell: |
        minikube start
        minikube ip

    - name: Clone the repository
      shell: |
        git clone https://github.com/shouryap1/Talent_Bridge_K8s.git
        cd Talent_Bridge_K8s

    - name: Set Kubernetes context to Minikube
      shell: |
        kubectl config use-context minikube

    - name: Scan frontend image with Trivy
      shell: |
        trivy image shouryap1/frontend:latest

    - name: Scan backend image with Trivy
      shell: |
        trivy image shouryap1/backend:latest

    - name: Apply Kubernetes configurations using Minikube's built-in kubectl
      shell: |
        kubectl apply -f Talent_Bridge_K8s/kub/ --validate=false

