---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
    - name: Start K8s
      service:
        name: K8s
        state: started

    - name: Clone the repository
      shell: git clone https://github.com/shouryap1/Talent_Bridge_K8s.git && cd Talent_Bridge_K8s
    
    - name: Scan frontend image
      shell: trivy image shouryap1/frontend:latest
    
    - name: Scan backend image
      shell: trivy image shouryap1/backend:latest

    - name: Run
      shell: kubectl apply -f kub/
