---
- name: Deploying with Kubernetes
  hosts: all
  tasks:
    - name: Install required dependencies for package installation
      apt:
        name:
          - wget
          - python3-dev
          - build-essential
        state: present
      become: yes
      become_method: sudo
      become_user: root

    - name: Download python3-openshift package
      get_url:
        url: "https://files.pythonhosted.org/packages/85/9e/d2cb07364b51ecb7e3efb2b95ab038e2890b8492f53ca42dce71d009d5da/python-openshift-0.14.0.tar.gz"
        dest: "/tmp/python-openshift-0.14.0.tar.gz"

    - name: Download python3-pyyaml package
      get_url:
        url: "https://files.pythonhosted.org/packages/01/7f/56a264e5c6f86a035ab2d3228792a77faddb380b1ea9eec9481efba9b0f9/PyYAML-5.4.1.tar.gz"
        dest: "/tmp/PyYAML-5.4.1.tar.gz"

    - name: Download python3-kubernetes package
      get_url:
        url: "https://files.pythonhosted.org/packages/29/a6/50f52e623aba7b45307387b179f6ed70006b4c5a2a03c2a39c387913564d/kubernetes-25.0.0.tar.gz"
        dest: "/tmp/kubernetes-25.0.0.tar.gz"

    - name: Install python3-openshift package
      shell: |
        cd /tmp
        tar -xzvf python-openshift-0.14.0.tar.gz
        cd python-openshift-0.14.0
        python3 setup.py install
      become: yes
      become_method: sudo
      become_user: root

    - name: Install python3-pyyaml package
      shell: |
        cd /tmp
        tar -xzvf PyYAML-5.4.1.tar.gz
        cd PyYAML-5.4.1
        python3 setup.py install
      become: yes
      become_method: sudo
      become_user: root

    - name: Install python3-kubernetes package
      shell: |
        cd /tmp
        tar -xzvf kubernetes-25.0.0.tar.gz
        cd kubernetes-25.0.0
        python3 setup.py install
      become: yes
      become_method: sudo
      become_user: root

    - name: Start Minikube
      shell: |
        minikube start
        minikube ip

    - name: Clone the repository
      git:
        repo: https://github.com/shouryap1/Talent_Bridge_K8s.git
        dest: /home/{{ ansible_user }}/Talent_Bridge_K8s
        clone: yes
        update: yes

    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/backend-deployment.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/backend-hpa.yaml') | from_yaml }}" 

    - name: Create Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/backend-secret.yaml') | from_yaml }}" 

    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/backend-service.yaml') | from_yaml }}"

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/frontend-deployment.yaml') | from_yaml }}"

    - name: Create Config Map
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/frontend-hpa.yaml') | from_yaml }}" 

    - name: Create Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/frontend-service.yaml') | from_yaml }}"
