---
- name: Deploying with Kubernetes
  hosts: all
  tasks:

    - name: Ensure pipx is installed
      apt:
        name: pipx
        state: present
      become: true

    - name: Install pre-requisites with pipx
      shell: |
        pipx install openshift pyyaml kubernetes
      become: true
      environment:
        PIPX_HOME: "/home/shourya/.local/pipx"
        PIPX_BIN_DIR: "/home/shourya/.local/bin"

    - name: Start Minikube
      shell: |
        minikube start
        minikube ip

    - name: Clone the repository
      shell: |
        git clone https://github.com/shouryap1/Talent_Bridge_K8s.git
        cd Talent_Bridge_K8s
        cd kub

    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'backend-deployment.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'backend-hpa.yaml') | from_yaml }}" 

    - name: Create Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'backend-secret.yaml') | from_yaml }}" 


    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'backend-service.yaml') | from_yaml }}"

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'frontend-deployment.yaml') | from_yaml }}"


    - name: Create Config Map
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'frontend-hpa.yaml') | from_yaml }}" 

    - name: Create Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'frontend-service.yaml') | from_yaml }}"
