---
- name: Deploying with Kubernetes
  hosts: all
  tasks:
    - name: Install required Python packages
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
        state: present
      become: yes
      become_method: sudo
      become_user: root
      # Do not hardcode the password in playbooks. Configure passwordless sudo or use vault

    - name: Start Minikube
      shell: |
        minikube start
        minikube ip

    - name: Clone the repository
      git:
        repo: https://github.com/shouryap1/Talent_Bridge_K8s.git
        dest: /home/{{ ansible_user }}/Talent_Bridge_K8s
        clone: yes
        update: yes

    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/backend-deployment.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/backend-hpa.yaml') | from_yaml }}" 

    - name: Create Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/backend-secret.yaml') | from_yaml }}" 

    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/backend-service.yaml') | from_yaml }}"

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/frontend-deployment.yaml') | from_yaml }}"

    - name: Create Config Map
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/frontend-hpa.yaml') | from_yaml }}" 

    - name: Create Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/{{ ansible_user }}/Talent_Bridge_K8s/kub/frontend-service.yaml') | from_yaml }}"
